version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  fastapi-todo-service:
    container_name: todo-api
    build:
      context: ./fastapi-todo-service
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - 8000:8000
    environment:
      ATLAS_URI: mongodb://root:password@mongodb:27017
      DB_NAME: todoapi

  next-todo-app:
    container_name: todo-client
    build:
      context: ./next-todo-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  api-gateway:
    container_name: nginx
    build:
      context: ./todo-api-gateway
      dockerfile: Dockerfile
    depends_on:
      - fastapi-todo-service
    ports:
      - 80:80

volumes:
  mongodb_data:
    driver: local
